Repository telbby/telbby-frontend, pull requests merged in 2021-11, with the labels that each got.

#6 스타일링 관련 기본 설정
  config/webpack/webpack.common.js
  public/favicon.ico
  public/favicon.png
  public/index.html
  src/@types/font.d.ts
  src/App.test.tsx
  src/App.tsx
  src/assets/.gitkeep
  src/assets/fonts/D2Coding.woff
  src/assets/fonts/D2CodingBold.woff
  src/index.tsx
  src/pages/CountPage/index.test.tsx
  src/pages/CountPage/index.tsx
  src/pages/CountPage/style.ts
  src/pages/HomePage/index.test.tsx
  src/pages/HomePage/index.tsx
  src/pages/HomePage/style.ts
  src/styles/emotion.d.ts
  src/styles/global.tsx
  src/styles/theme.ts
Labels: styling✨

#11 공통 컴포넌트 작업
  src/@types/image.d.ts
  src/App.test.tsx
  src/App.tsx
  src/assets/images/logo.png
  src/assets/images/page-not-found.png
  src/components/Navigation/index.test.tsx
  src/components/Navigation/index.tsx
  src/components/common/Footer/index.test.tsx
  src/components/common/Footer/index.tsx
  src/components/common/Footer/style.ts
  src/components/common/Jumbotron/index.test.tsx
  src/components/common/Jumbotron/index.tsx
  src/components/common/Jumbotron/style.ts
  src/components/common/Layout/index.test.tsx
  src/components/common/Layout/index.tsx
  src/components/common/Layout/style.ts
  src/components/common/Logo/index.test.tsx
  src/components/common/Logo/index.tsx
  src/components/common/Logo/style.ts
  src/components/common/Navbar/index.test.tsx
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/style.ts
  src/constants/uri.ts
  src/pages/CountPage/index.test.tsx
  src/pages/CountPage/index.tsx
  src/pages/HomePage/index.test.tsx
  src/pages/HomePage/index.tsx
  src/pages/HomePage/style.ts
  src/pages/NotFoundPage/index.test.tsx
  src/pages/NotFoundPage/index.tsx
  src/pages/NotFoundPage/style.ts
  src/styles/global.tsx
  src/styles/theme.ts
Labels: feature

#15 회원가입 사용자 정보 validation 추가
  src/constants/validation.ts
  src/utils/validation/common/index.test.ts
  src/utils/validation/common/index.ts
  src/utils/validation/idValidation/index.test.ts
  src/utils/validation/idValidation/index.ts
  src/utils/validation/index.ts
  src/utils/validation/pwValidation/index.test.ts
  src/utils/validation/pwValidation/index.ts
Labels: feature

#12 인증 관련 API 요청 구현
  .mock.env
  package.json
  src/apis/.gitkeep
  src/apis/api.ts
  src/apis/authApi/index.test.ts
  src/apis/authApi/index.ts
  src/apis/index.ts
  src/apis/userApi/index.test.ts
  src/apis/userApi/index.ts
  src/atoms/userState.ts
  src/constants/error.ts
  src/hooks/.gitkeep
  src/hooks/useAuth.ts
  src/hooks/useAutoLogin.ts
  src/hooks/useSignup.ts
  src/types/auth.ts
  src/types/index.ts
  src/types/user.ts
  src/utils/httpClient/axiosHTTPClient.ts
  src/utils/httpClient/httpClient.ts
  src/utils/httpClient/httpError.ts
  src/utils/httpClient/index.ts
  src/utils/httpClient/types.ts
  yarn.lock
Labels: feature

#13 Shell Component 구현
  package.json
  src/components/Shell/index.test.tsx
  src/components/Shell/index.tsx
  src/components/Shell/style.ts
  src/components/ShellLine/index.test.tsx
  src/components/ShellLine/index.tsx
  src/components/ShellLine/style.ts
  src/constants/shell.ts
  src/hooks/useArrayIterator.ts
  src/pages/HomePage/index.tsx
  yarn.lock
Labels: feature

#25 Confirm 모달 구현
  .prettierrc
  config/.lintstagedrc.json
  config/webpack/webpack.common.js
  package.json
  public/index.html
  src/atoms/confirmModalState.ts
  src/components/common/Portal/index.ts
  src/components/modal/ConfirmModal/index.test.tsx
  src/components/modal/ConfirmModal/index.tsx
  src/components/modal/ConfirmModal/style.ts
  src/components/modal/ConfirmModalRoot/index.tsx
  src/components/modal/ModalPortal/index.tsx
  src/hooks/useConfirmModal.ts
  src/index.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: feature

#28 Snackbar 구현
  src/atoms/confirmModalState.ts
  src/atoms/snackbarState.ts
  src/components/modal/ConfirmModal/index.tsx
  src/components/modal/Snackbar/index.test.tsx
  src/components/modal/Snackbar/index.tsx
  src/components/modal/Snackbar/style.ts
  src/components/modal/SnackbarRoot/index.tsx
  src/hooks/useSnackbar.ts
  src/index.tsx
  src/styles/zIndexes.ts
Labels: feature

#30 비밀번호 데이터 검증 부분에서 조합 체크 오류 해결
  src/utils/validation/common/index.test.ts
  src/utils/validation/common/index.ts
  src/utils/validation/pwValidation/index.test.ts
  src/utils/validation/pwValidation/index.ts
Labels: bug

#23 Telbby 서비스 소개 UI 구현
  package.json
  src/assets/images/intro-client-ui.png
  src/assets/images/intro-feedback-system.png
  src/components/intro/InduceSignup/index.test.tsx
  src/components/intro/InduceSignup/index.tsx
  src/components/intro/InduceSignup/style.ts
  src/components/intro/IntroMain/index.test.tsx
  src/components/intro/IntroMain/index.tsx
  src/components/intro/IntroMain/style.ts
  src/components/intro/IntroSection/index.test.tsx
  src/components/intro/IntroSection/index.tsx
  src/components/intro/IntroSection/style.ts
  src/components/intro/IntroTitle/index.test.tsx
  src/components/intro/IntroTitle/index.tsx
  src/components/intro/IntroTitle/style.ts
  src/components/intro/IntroWithClientUI/index.test.tsx
  src/components/intro/IntroWithClientUI/index.tsx
  src/components/intro/IntroWithClientUI/style.ts
  src/components/intro/IntroWithFeedbackSystem/index.test.tsx
  src/components/intro/IntroWithFeedbackSystem/index.tsx
  src/components/intro/IntroWithFeedbackSystem/style.ts
  src/pages/HomePage/index.test.tsx
  src/pages/HomePage/index.tsx
  src/styles/breakPoints.ts
  src/styles/emotion.d.ts
  src/styles/media.ts
  src/styles/theme.ts
  yarn.lock
Labels: feature

#20 회원가입 페이지, 로그인 페이지 개발
  package.json
  src/App.tsx
  src/apis/authApi/index.ts
  src/components/Shell/index.test.tsx
  src/components/Shell/index.tsx
  src/components/Shell/shellFormElement.ts
  src/components/Shell/style.ts
  src/components/ShellLine/index.test.tsx
  src/components/ShellLine/index.tsx
  src/components/ShellLine/style.ts
  src/components/intro/IntroMain/index.tsx
  src/constants/shell.ts
  src/constants/uri.ts
  src/pages/HomePage/index.tsx
  src/pages/SigninPage/index.test.tsx
  src/pages/SigninPage/index.tsx
  src/pages/SigninPage/style.ts
  src/pages/SignupPage/index.test.tsx
  src/pages/SignupPage/index.tsx
  src/pages/SignupPage/style.ts
  src/utils/httpClient/axiosHTTPClient.ts
  yarn.lock
Labels: feature
