Repository telbby/telbby-frontend, pull requests merged in 2021-12, with the labels that each got.

#37 [#36] auto assign 기능 추가
  .github/auto_assign.yml
Labels: chore

#35 서비스 페이지 UI 작업
  README.md
  src/App.tsx
  src/assets/images/empty.png
  src/assets/images/remove.png
  src/components/Shell/index.test.tsx
  src/components/Shell/index.tsx
  src/components/Shell/style.ts
  src/components/common/Jumbotron/style.ts
  src/components/intro/InduceSignup/style.ts
  src/components/intro/IntroMain/index.tsx
  src/components/intro/IntroMain/style.ts
  src/components/intro/IntroSection/style.ts
  src/components/intro/IntroTitle/style.ts
  src/components/intro/IntroWithClientUI/index.tsx
  src/components/intro/IntroWithFeedbackSystem/index.tsx
  src/components/service/ServiceItem/index.test.tsx
  src/components/service/ServiceItem/index.tsx
  src/components/service/ServiceItem/style.ts
  src/components/service/ServiceList/index.test.tsx
  src/components/service/ServiceList/index.tsx
  src/components/service/ServiceList/style.ts
  src/constants/uri.ts
  src/pages/NotFoundPage/style.ts
  src/pages/ServicePage/dummyData.ts
  src/pages/ServicePage/index.test.tsx
  src/pages/ServicePage/index.tsx
  src/pages/ServicePage/style.ts
  src/pages/SigninPage/index.tsx
  src/pages/SignupPage/index.tsx
Labels: feature

#40 8주차 sprint merge
  README.md
  src/App.tsx
  src/assets/images/empty.png
  src/assets/images/remove.png
  src/components/Shell/index.test.tsx
  src/components/Shell/index.tsx
  src/components/Shell/style.ts
  src/components/common/Jumbotron/style.ts
  src/components/intro/InduceSignup/style.ts
  src/components/intro/IntroMain/index.tsx
  src/components/intro/IntroMain/style.ts
  src/components/intro/IntroSection/style.ts
  src/components/intro/IntroTitle/style.ts
  src/components/intro/IntroWithClientUI/index.tsx
  src/components/intro/IntroWithFeedbackSystem/index.tsx
  src/components/service/ServiceItem/index.test.tsx
  src/components/service/ServiceItem/index.tsx
  src/components/service/ServiceItem/style.ts
  src/components/service/ServiceList/index.test.tsx
  src/components/service/ServiceList/index.tsx
  src/components/service/ServiceList/style.ts
  src/constants/uri.ts
  src/pages/NotFoundPage/style.ts
  src/pages/ServicePage/dummyData.ts
  src/pages/ServicePage/index.test.tsx
  src/pages/ServicePage/index.tsx
  src/pages/ServicePage/style.ts
  src/pages/SigninPage/index.tsx
  src/pages/SignupPage/index.tsx
Labels: sprint-complete

#39 transpiler swc로 변경
  config/.babel.config.json
  config/.swcrc
  config/jest.config.js
  config/webpack/paths.js
  config/webpack/webpack.common.js
  package.json
  yarn.lock
Labels: chore

#44 Shell Component 계층 수정
  src/components/intro/IntroMain/index.tsx
  src/components/shell/Shell/index.test.tsx
  src/components/shell/Shell/index.tsx
  src/components/shell/Shell/shellFormElement.ts
  src/components/shell/Shell/style.ts
  src/components/shell/ShellLine/index.test.tsx
  src/components/shell/ShellLine/index.tsx
  src/components/shell/ShellLine/style.ts
  src/pages/ServicePage/index.tsx
  src/pages/SigninPage/index.tsx
  src/pages/SignupPage/index.tsx
Labels: chore

#47 ErrorBoundary 생성
  src/App.tsx
  src/components/common/ErrorBoundary/index.test.tsx
  src/components/common/ErrorBoundary/index.tsx
Labels: feature

#52 로그인 상태에 따른 Route 처리 및 NavBar 렌더링 처리
  .eslintrc.js
  src/App.test.tsx
  src/App.tsx
  src/components/common/Layout/index.test.tsx
  src/components/common/Navbar/index.test.tsx
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/style.ts
  src/components/common/PrivateRoute/index.test.tsx
  src/components/common/PrivateRoute/index.tsx
  src/components/nav/PrivateNavbar/index.test.tsx
  src/components/nav/PrivateNavbar/index.tsx
  src/components/nav/PublicNavbar/index.test.tsx
  src/components/nav/PublicNavbar/index.tsx
  src/components/nav/style.ts
  src/pages/HomePage/index.test.tsx
  src/pages/NotFoundPage/index.test.tsx
  src/pages/ServicePage/index.test.tsx
  src/pages/SigninPage/index.tsx
Labels: feature

#48 Silent Refresh 로직 구현
  src/apis/api.ts
  src/apis/api/index.test.ts
  src/apis/api/index.ts
  src/apis/api/types.ts
  src/apis/authApi/index.test.ts
  src/apis/authApi/index.ts
  src/apis/userApi/index.test.ts
  src/apis/userApi/index.ts
  src/types/auth.ts
  src/utils/httpClient/axiosHTTPClient.ts
  src/utils/httpClient/httpClient.ts
  src/utils/httpClient/httpError.ts
  src/utils/httpClient/types.ts
Labels: feature

#54 storybook 환경 설정
  .github/workflows/chromatic.yml
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/components/modal/Snackbar/index.tsx
  src/stories/Page.stories.tsx
  yarn.lock
Labels: chore

#58 회원가입, 로그인 페이지에서 홈 링크 추가
  src/pages/SigninPage/index.test.tsx
  src/pages/SigninPage/index.tsx
  src/pages/SignupPage/index.test.tsx
  src/pages/SignupPage/index.tsx
  src/pages/SignupPage/style.ts
Labels: feature

#57 서비스 수정 페이지 마크업
  src/App.tsx
  src/assets/images/theme1.png
  src/assets/images/theme2.png
  src/components/service/ServiceEditForm/index.tsx
  src/components/service/ServiceEditForm/style.ts
  src/constants/uri.ts
  src/pages/ServiceEditPage/dummyData.ts
  src/pages/ServiceEditPage/index.tsx
  src/styles/global.tsx
  src/types/service.ts
Labels: feature

#56 쉘 컴포넌트 로직 개선
  src/components/intro/IntroMain/index.tsx
  src/components/shell/Shell/index.test.tsx
  src/components/shell/Shell/index.tsx
  src/components/shell/Shell/shellFormElement.ts
  src/components/shell/ShellLine/index.test.tsx
  src/components/shell/ShellLine/index.tsx
  src/components/shell/ShellPrintLine/index.tsx
  src/components/shell/ShellPrintLine/style.ts
  src/components/shell/ShellReadLine/index.tsx
  src/components/shell/ShellReadLine/style.ts
  src/components/shell/helper.ts
  src/components/shell/types.ts
  src/hooks/useFocusOnLastInput.ts
  src/hooks/useShellLine.ts
  src/pages/ServicePage/index.tsx
  src/pages/SigninPage/index.tsx
  src/pages/SignupPage/index.tsx
Labels: refactor, discussion ⚒
